language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t danielnuess/docker-react-f Dockerfile.dev .

script:
    - docker run -e CI=true danielnuess/docker-react npm run test -- --coverage